# Generated by Django 3.2.5 on 2022-02-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20220222_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='single_order',
            new_name='order',
        ),
    ]
