# Generated by Django 3.2.5 on 2022-02-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_rename_single_order_orderlineitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orginal_bag',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_pid',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
